In [2]:
import pandas as pd

In [3]:
copacabana = pd.read_csv('copacabana.csv', delimiter=';')

In [4]:
copacabana.columns

Index(['Posicao', 'Quartos', 'Vagas', 'DistIpanema', 'DistPraia', 'DistFavela',
       'RendaMedia', 'RendaMovel', 'RendaMovelRua', 'Vu2009', 'Mes', 'Idade',
       'Tipologia', 'AreaConstruida', 'VAL_UNIT', 'X', 'Y'],
      dtype='object')

In [5]:
copacabana['Quartos'].describe()

count    1675.000000
mean        1.767510
std         1.142523
min         0.010000
25%         1.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: Quartos, dtype: float64

In [6]:
copacabana['Quartos'] > 3

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1645    False
1646    False
1647    False
1648    False
1649    False
1650    False
1651    False
1652    False
1653    False
1654     True
1655    False
1656    False
1657    False
1658    False
1659    False
1660    False
1661    False
1662    False
1663    False
1664    False
1665    False
1666    False
1667    False
1668    False
1669    False
1670    False
1671    False
1672    False
1673    False
1674    False
Name: Quartos, Length: 1675, dtype: bool

In [8]:
copacabana.loc[copacabana['Quartos'] == 6]

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
748,1,6.0,2.0,2500,35,743,1524600,1275377,1399989,4100,360,58.0,1,668,4491,686456.25,7458801.05

In [10]:
copacabana.loc[copacabana['Quartos'] > 4]

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
173,1,5.0,0.01,2696,154,712,1083455,649733,866594,2000,425,55.0,1,38,6316,686522.9800,7458989.87
748,1,6.0,2.00,2500,35,743,1524600,1275377,1399989,4100,360,58.0,1,668,4491,686456.2500,7458801.05
1521,1,5.0,3.00,3044,31,609,1524600,1168222,1346411,4100,405,34.0,1,430,5000,686965.3201,7459109.71

In [12]:
copacabana['AreaConstruida'] * copacabana['VAL_UNIT']

0        416005
1        460009
2        720012
3        990000
4        909976
5        790024
6        670015
7        249990
8        319990
9        299997
10       390000
11       299992
12       410000
13       749990
14       625022
15       619972
16       309986
17       340032
18       760000
19       870020
20       250005
21       340005
22       210000
23       139995
24       270000
25        90000
26       350010
27       450022
28       329975
29       210033
         ...
1645     792984
1646    1393956
1647     810027
1648    1800022
1649     886990
1650     969992
1651     499968
1652     560032
1653     284984
1654    2199998
1655    2179944
1656     300011
1657     180000
1658     280016
1659     229992
1660     342012
1661     699996
1662     710024
1663    1320000
1664     300024
1665     700024
1666     390000
1667     434980
1668     219996
1669     639975
1670     479940
1671     402040
1672     600020
1673     766705
1674     683871
Length: 1675, dtype: int64

In [13]:
copacabana['TOTAL'] = copacabana['AreaConstruida'] * copacabana['VAL_UNIT']
copacabana

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y,TOTAL
0,1,3.00,0.01,1144,311,146,969501,1028834,999168,1750,509,37.00,1,95,4379,685365.0700,7457802.680,416005
1,0,2.00,0.01,2456,502,254,1472861,1137759,1305310,2300,484,30.00,1,71,6479,685941.5500,7459001.320,460009
2,0,2.00,0.01,2448,772,229,1803724,1512475,1658100,2350,920,44.00,1,58,12414,685627.3900,7459080.520,720012
3,0,2.00,0.01,1615,428,310,1124331,1370600,1247466,2200,930,43.00,1,88,11250,685438.2001,7458268.280,990000
4,0,2.00,1.00,2358,586,287,1165764,1177933,1171849,2150,918,42.00,1,68,13382,685764.3840,7458954.513,909976
5,0,2.00,1.00,2358,586,287,1165764,1177933,1171849,2150,825,42.00,1,68,11618,685764.3840,7458954.513,790024
6,0,3.00,0.01,2537,758,115,994427,1037602,1016015,1850,864,43.00,1,103,6505,685723.3600,7459150.250,670015
7,0,0.01,0.01,555,332,306,1140573,1064998,1102786,2450,554,40.00,2,39,6410,685263.3300,7457221.990,249990
8,0,1.00,0.01,555,332,306,1140573,1064998,1102786,2450,830,43.00,1,22,14545,685263.3300,7457221.990,319990
9,0,1.00,0.01,555,332,306,1140573,1064998,1102786,2450,940,43.00,1,27,11111,685263.3300,7457221.990,299997
10,1,1.00,0.01,555,332,306,1140573,1064998,1102786,2450,918,43.00,1,20,19500,685263.3300,7457221.990,390000
11,1,0.01,0.01,555,332,306,1140573,1064998,1102786,2450,918,43.00,1,22,13636,685263.3300,7457221.990,299992
12,1,0.01,0.01,555,332,306,1140573,1064998,1102786,2450,864,43.00,1,20,20500,685263.3300,7457221.990,410000
13,1,3.00,1.00,2498,716,148,1281444,1281444,1281444,1900,830,43.00,1,74,10135,685737.4900,7459106.520,749990
14,1,2.00,0.01,2498,716,148,1281444,1281444,1281444,1900,830,43.00,1,62,10081,685737.4900,7459106.520,625022
15,1,2.00,0.01,2498,716,148,1281444,1281444,1281444,1900,920,43.00,1,59,10508,685737.4900,7459106.520,619972
16,0,2.00,1.00,2498,716,148,1281444,1281444,1281444,1900,360,40.00,1,74,4189,685737.4900,7459106.520,309986
17,0,2.00,0.01,2835,330,629,1124331,727350,925841,2100,385,40.00,1,64,5313,686482.9500,7459173.830,340032
18,1,2.00,2.00,2835,330,629,1124331,727350,925841,2100,918,43.00,1,64,11875,686482.9500,7459173.830,760000
19,0,3.00,0.01,1987,494,510,1369604,1453409,1411507,2600,920,44.00,1,82,10610,685585.7600,7458617.750,870020
20,1,0.01,0.01,2057,307,621,1395924,1176888,1286406,2350,792,43.00,2,15,16667,685829.6300,7458617.410,250005
21,1,0.01,0.01,2057,307,621,1395924,1176888,1286406,2350,801,43.00,1,15,22667,685829.6300,7458617.410,340005
22,0,1.00,0.01,2057,307,621,1395924,1176888,1286406,2350,573,41.00,1,15,14000,685829.6300,7458617.410,210000
23,1,1.00,0.01,2057,307,621,1395924,1176888,1286406,2350,425,41.00,2,15,9333,685829.6300,7458617.410,139995
24,1,0.01,0.01,2057,307,621,1395924,1176888,1286406,2350,801,43.00,2,15,18000,685829.6300,7458617.410,270000
25,1,1.00,0.01,2057,307,621,1395924,1176888,1286406,2350,405,41.00,1,20,4500,685829.6300,7458617.410,90000
26,1,3.00,0.01,3207,145,467,1083455,1041944,1062700,2000,509,53.00,1,90,3889,687024.5600,7459269.140,350010
27,0,2.00,0.01,474,212,492,1308645,1445903,1377274,2100,554,38.00,1,58,7759,685416.7700,7457059.020,450022
28,0,2.00,0.01,1191,564,125,2068724,2135043,2101884,2450,445,40.00,1,67,4925,685122.0745,7457874.874,329975
29,0,2.00,0.01,2536,817,156,1165764,881744,1023754,2150,360,40.00,1,81,2593,685652.6700,7459165.230,210033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,1,1.00,0.01,1565,702,44,1286868,999741,1143305,1850,904,75.00,1,57,13912,685119.5800,7458248.830,792984
1646,1,2.00,0.01,1565,702,44,1286868,999741,1143305,1850,904,75.00,1,108,12907,685119.5800,7458248.830,1393956
1647,1,1.00,1.00,1565,702,44,1286868,999741,1143305,1850,920,75.00,1,57,14211,685119.5800,7458248.830,810027
1648,1,3.00,0.01,1565,702,44,1286868,999741,1143305,1850,904,75.00,1,133,13534,685119.5800,7458248.830,1800022
1649,1,1.00,1.00,1565,702,44,1286868,999741,1143305,1850,864,75.00,1,65,13646,685119.5800,7458248.830,886990
1650,0,2.00,2.00,2650,419,381,1357174,1650214,1503694,2500,842,17.00,1,74,13108,686211.6000,7459102.200,969992
1651,0,2.00,2.00,2650,419,381,1357174,1650214,1503694,2500,554,14.00,1,72,6944,686211.6000,7459102.200,499968
1652,0,2.00,2.00,2650,419,381,1357174,1650214,1503694,2500,484,14.00,1,74,7568,686211.6000,7459102.200,560032
1653,0,1.00,0.01,791,445,47,1056413,1199919,1128166,800,825,17.00,1,49,5816,685153.1000,7457474.120,284984
1654,0,4.00,3.00,2442,894,189,1783469,1696269,1739869,2300,920,12.00,1,166,13253,685475.4576,7459100.927,2199998
1655,1,2.00,2.00,2853,530,436,1915512,2246429,2080971,2450,930,12.00,1,156,13974,686292.3707,7459288.323,2179944
1656,1,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,385,7.00,1,43,6977,685816.0100,7458204.550,300011
1657,1,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,405,7.00,1,48,3750,685816.0100,7458204.550,180000
1658,0,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,573,7.00,1,37,7568,685816.0100,7458204.550,280016
1659,0,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,573,7.00,1,37,6216,685816.0100,7458204.550,229992
1660,0,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,445,7.00,1,44,7773,685816.0100,7458204.550,342012
1661,0,1.00,0.01,1669,69,693,1447740,1271491,1359616,2700,862,10.00,1,44,15909,685816.0100,7458204.550,699996
1662,1,3.00,2.00,2564,949,183,1803724,1724790,1764257,2350,425,7.00,1,124,5726,685515.4500,7459218.860,710024
1663,1,2.00,2.00,2391,856,182,1395924,2123522,1759723,1550,792,9.00,1,96,13750,685479.2401,7459049.260,1320000
1664,1,1.00,0.01,1163,377,143,969501,996033,982767,1750,509,6.00,3,54,5556,685305.1601,7457833.150,300024
1665,1,1.00,0.01,1163,377,143,969501,996033,982767,1750,862,9.00,3,52,13462,685305.1601,7457833.150,700024
1666,1,2.00,0.01,1163,377,143,969501,996033,982767,1750,445,6.00,3,52,7500,685305.1601,7457833.150,390000
1667,1,1.00,1.00,1163,377,143,969501,996033,982767,1750,573,6.00,3,52,8365,685305.1601,7457833.150,434980
1668,1,2.00,2.00,604,542,106,1056413,1252054,1154234,800,360,5.00,1,81,2716,685047.7900,7457283.270,219996
1669,0,2.00,2.00,2866,562,416,1915512,2101848,2008680,2450,554,2.00,1,75,8533,686269.4600,7459312.080,639975
1670,1,2.00,2.00,2866,562,416,1915512,2101848,2008680,2450,360,2.00,1,114,4210,686269.4600,7459312.080,479940
1671,1,2.00,2.00,2488,1030,106,1395924,1396219,1396072,1550,509,0.01,1,95,4232,685346.9700,7459162.110,402040
1672,1,2.00,2.00,2488,1030,106,1395924,1396219,1396072,1550,509,0.01,1,95,6316,685346.9700,7459162.110,600020
1673,1,2.00,2.00,2488,1030,106,1395924,1396219,1396072,1550,445,0.01,1,113,6785,685346.9700,7459162.110,766705
1674,1,2.00,2.00,2488,1030,106,1395924,1396219,1396072,1550,445,0.01,1,101,6771,685346.9700,7459162.110,683871

In [15]:
copacabana['TOTAL'].tail()

1670    479940
1671    402040
1672    600020
1673    766705
1674    683871
Name: TOTAL, dtype: int64